# Replace <github-username> with your username and choose branch name (main)
git init
git checkout -b main
git add .
git commit -m "Initial commit â€” MoneyTransfer POC with composite scoring & multi-LLM"
git remote add origin https://github.com/<github-SrimantN>/moneytransfer-poc.git
git push -u origin main
